version: '2'
services:
  php:
    container_name: test-php
    image: php:fpm
    volumes:
      - ./src:/var/www/html/site
  nginx:
    container_name: test-nginx
    image: nginx:latest
    volumes:
      - ./src:/var/www/html/site
      - ./.nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 80:80
